name: e_commerce_app
# The name of the package. This is used to identify your package when it is published.
description: A modern e-commerce app built with Flutter and Supabase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.5.4
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.1
  uuid: ^4.5.1
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/.env
